### ISSUE TITLE
Package test error

### ISSUE THREAD

**Issue by macsj200** [aldeed/meteor-browser-tests#5] opened 2017-04-21 13:49 UTC
The command `TEST_BROWSER_DRIVER=chrome meteor test-packages --driver-package dispatch:mocha` fails with the error message `Error: When running tests with TEST_BROWSER_DRIVER=chrome, you must first "npm i --save-dev selenium-webdriver chromedriver"`. I've already run this command and installed the dependencies. This seems like an issue with the way dependencies are loaded when using `test-packages` vs `test`. Do you have any ideas how to fix this issue?

**Comment by macsj200** [comment] 2017-04-21 13:51
I suppose this is the offending line https://github.com/aldeed/meteor-browser-tests/blob/b1c6924099d07b37c1f9eedb0e6f64036be6c4b1/browser/chromedriver.js#L29

**Comment by aldeed** [comment] 2017-04-24 14:17
@macsj200 See https://github.com/meteor/meteor/issues/8577

Your meteor/meteor issue is a duplicate of that

**Closed by aldeed** 2017-04-24 14:17 UTC
